version: '3'
services:
  script:
    build: .
    volumes:
      - ./:/app
    environment:
      - PROJECT: ${PROJECT}
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2000M

    # env_file:
    #   - .env